const MS = 1;
const SECOND = 1000 * MS;
const MINUTE = 60 * SECOND;

module.exports = {
  MS,
  SECOND,
  MINUTE,

  ONE_IOTA: 1,
  ONE_KIOTA: 1000,
  ONE_MIOTA: 1000000,
  ONE_GIOTA: 1000000000,

  DUSTALLOWANCE_REFRESH_INTERVAL: 1 * MINUTE,
  BALANCE_REFRESH_INTERVAL: 5 * MINUTE,
  GETINFO_REFRESH_INTERVAL: 2 * MINUTE,
  VALUESPAM_REFRESH_INTERVAL: 30 * SECOND,

  N_ACCOUNTS: 2,
};
